### ISSUE TITLE
Improve canceling via Ctrl+C

### ISSUE THREAD

**Issue by lantiga** [Lightning-AI/LitServe#11]
Right now the server hangs after keyboard interrupt with

```
ERROR:    Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/starlette/routing.py", line 743, in lifespan
    await receive()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError
```

This may be related to cancelling async tasks.

We need to handle termination gracefully.

**Comment by aniketmaurya** [comment]
maybe related to this, right now I am facing the following error on keyboard interupt 

```^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [22155]
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/lit.py", line 112, in <module>
    ).clone()
  File "/teamspace/studios/this_studio/litserve/src/litserve/server.py", line 421, in run
    uvicorn.run(host="0.0.0.0", port=port, app=self.app, log_level=log_level, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
^CException ignored in atexit callback: <function _exit_function at 0x7f940aea30a0>
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)```

**Comment by aniketmaurya** [comment]
Closing this issue since we don't get the server hanging issue anymore. Please reopen if this issue comes again.
