### ISSUE TITLE
CUDA Multiprocessing Issue

### ISSUE THREAD

**Issue by floschne** [Lightning-AI/LitServe#321]
## 🐛 Bug

I'm trying to build a simple SigLIP Inference API with LitServ but I'm running into the well-known CUDA vs multiprocessing issue (`Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method`).

Does anyone know how to solve this? Setting the `spawn` forking method via torch (`torch.set_start_method('spawn')` does not work. No matter if I run it before or after `import litserve as ls`

```bash
❯ CUDA_VISIBLE_DEVICES=4 python server.py
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
Swagger UI is available at http://0.0.0.0:8000/docs
INFO:     Started server process [546581]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Using device: cuda:0
You are attempting to use Flash Attention 2.0 without specifying a torch dtype. This might lead to unexpected behaviour
Setup complete for worker 0.
LitAPI ran into an error while processing the request uid=d1cab0c9-a28c-42c2-b438-4697bc14bf21.
Please check the error trace for more details.
Traceback (most recent call last):
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/litserve/loops.py", line 149, in run_single_loop
    response_queues[response_queue_id].put((uid, (y_enc, LitAPIStatus.OK)))
  File "<string>", line 2, in put
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/multiprocessing/managers.py", line 833, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/multiprocessing/managers.py", line 253, in serve_client
    request = recv()
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 148, in rebuild_cuda_tensor
    torch.cuda._lazy_init()
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/torch/cuda/__init__.py", line 300, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
---------------------------------------------------------------------------
INFO:     127.0.0.1:56904 - "POST /predict HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 20, in __call__
    await responder(scope, receive, send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 39, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/litserve/server.py", line 346, in predict
    load_and_raise(response)
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/litserve/utils.py", line 58, in load_and_raise
    raise exception
multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/multiprocessing/managers.py", line 253, in serve_client
    request = recv()
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 148, in rebuild_cuda_tensor
    torch.cuda._lazy_init()
  File "/ltstorage/home/7schneid/miniforge3/envs/murag/lib/python3.10/site-packages/torch/cuda/__init__.py", line 300, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
---------------------------------------------------------------------------
```

### MWE to reproduce

```python
# server.py
import base64
import io

import torch
from PIL import Image
from transformers import SiglipModel, SiglipProcessor
import litserve as ls


MODEL_NAME = "google/siglip-so400m-patch14-384"
TORCH_DTYPE = torch.bfloat16


class SigLipLitAPI(ls.LitAPI):
    def setup(self, device: str):
        self.device = device
        print(f"Using device: {device}")
        self.model = SiglipModel.from_pretrained(
            MODEL_NAME,
            attn_implementation="flash_attention_2",
            torch_dtype=TORCH_DTYPE,
            device_map=device,
        )
        self.processor = SiglipProcessor.from_pretrained(MODEL_NAME)

    def _compute_text_embedding(self, text_inputs) -> torch.Tensor:
        with torch.no_grad():
            with torch.autocast(self.device):
                text_emb = self.model.get_text_features(**text_inputs.to(self.device))
        return text_emb

    def _compute_image_embedding(self, image_inputs) -> torch.Tensor:
        with torch.no_grad():
            with torch.autocast(self.device):
                img_emb = self.model.get_image_features(**image_inputs.to(self.device))
        return img_emb

    def decode_request(self, request):
        image_inputs, text_inputs = None, None
        if "image_bytes" in request:
            b64 = request["image_bytes"]
            image = Image.open(io.BytesIO(base64.b64decode(b64)))
            image_inputs = self.processor(
                images=image, padding="max_length", return_tensors="pt"
            )  # type: ignore
        if "text" in request:
            text = request["text"]
            text_inputs = self.processor(
                text=text, padding="max_length", return_tensors="pt"
            )  # type: ignore

        return image_inputs, text_inputs

    def predict(self, inputs):
        image, text = inputs
        img_emb, text_emb = None, None
        if image is not None:
            img_emb = self._compute_image_embedding(image)
        if text is not None:
            text_emb = self._compute_text_embedding(text)
        return img_emb, text_emb

    def encode_response(self, outputs):
        img_emb, text_emb = outputs
        return {"image_embedding": img_emb, "text_embedding": text_emb}


if __name__ == "__main__":
    api = SigLipLitAPI()
    server = ls.LitServer(api, accelerator="cuda")
    server.run(port=8000)
```

```python
# client.py

import requests
import base64
import io
from PIL import Image

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw).convert("RGB")

buffered = io.BytesIO()
image.save(buffered, format="JPEG")
b64 = base64.b64encode(buffered.getvalue()).decode("utf-8")

data = {
    "image_bytes": b64,
    "text": "A quick brown fox jumps over the lazy dog",
}
response = requests.post("http://127.0.0.1:58007/predict", json=data)
print(response.json())
```

### Expected behavior

The serialized embeddings are printed .

### Environment
- PyTorch/Jax/Tensorflow Version (e.g., 1.0): 2.4.0
- OS (e.g., Linux): Ubuntu 22.04 LTS
- How you installed PyTorch (`conda`, `pip`, source): conda
- Python version: 3.11
- CUDA/cuDNN version: 12.4
- GPU models and configuration: Using one single A100
- Any other relevant information: LitServ version 0.2.3

**Comment by aniketmaurya** [comment]
hi @floschne, thanks for reporting the issue! It seems like a torch.Tensor object is being returned from the `encode_response` method. Could you try converting them to list?

**Comment by floschne** [comment]
Oh, true, I missed that! It works like a charm now! Thanks
