### ISSUE TITLE
Too many files open with 1K requests

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/LitServe#88]
Sending request to `request_buffer` creates a new pipe and too many requests causes `OS too many files open` error
```py
self.app.request_buffer[uid] = (await request.json(), write)
```

cc: @lantiga 

---
```
INFO:     127.0.0.1:45038 - "POST /predict HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pycharm_project_34/src/litserve/server.py", line 395, in predict
    self.app.request_buffer[uid] = (await request.json(), write)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "<string>", line 2, in __setitem__
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/multiprocessing/managers.py", line 820, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/multiprocessing/connection.py", line 1172, in reduce_connection
    df = reduction.DupFd(conn.fileno())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aniket/miniconda3/envs/am/lib/python3.12/multiprocessing/resource_sharer.py", line 48, in __init__
    new_fd = os.dup(fd)
             ^^^^^^^^^^
OSError: [Errno 24] Too many open files
```

**Comment by lantiga** [comment]
Cloud you reproduce @aniketmaurya?

**Comment by aniketmaurya** [comment]
unfortunately no, even after running the server for more than 10-20K requests. I guess earlier my system had some zombie processes from older LitServe version.

**Comment by lantiga** [comment]
Ok let’s close
